spring:
  application:
    name: hystrix-dashboard-local

#----------------------------------------------------------------------------------------------------------------------------------------------------------------
# Turbine Options
#----------------------------------------------------------------------------------------------------------------------------------------------------------------

turbine:
  app-config: ZUUL-SERVER-LOCAL,CUSTOMER-SERVICE,ORDER-SERVICE
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")

#----------------------------------------------------------------------------------------------------------------------------------------------------------------
# Endpoint output options for Hystrix Stream
#----------------------------------------------------------------------------------------------------------------------------------------------------------------

management:
  endpoints:
    web:
      exposure:
        include: "*"
